{{- if and .Values.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.secretName" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ include "rabbitmq.auth.username" . | b64enc | quote }}
  password: {{ include "rabbitmq.auth.password" . | b64enc | quote }}
  erlang-cookie: {{ include "rabbitmq.auth.erlangCookie" . | b64enc | quote }}
{{- end }}
