apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taiga.appSecretName" . }}
  labels:
    {{- include "taiga.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ include "taiga.secretKeyValue" . | b64enc | quote }}
