{{- if .Values.enabled }}
{{- $script := printf "DO\n$$\nBEGIN\n   IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '%s') THEN\n      CREATE ROLE \"%s\" LOGIN PASSWORD '%s';\n   ELSE\n      ALTER ROLE \"%s\" WITH PASSWORD '%s';\n   END IF;\nEND\n$$;\n\nDO\n$$\nBEGIN\n   IF NOT EXISTS (SELECT FROM pg_database WHERE datname = '%s') THEN\n      CREATE DATABASE \"%s\";\n   END IF;\n   ALTER DATABASE \"%s\" OWNER TO \"%s\";\nEND\n$$;\n" .Values.auth.username .Values.auth.username .Values.auth.password .Values.auth.username .Values.auth.password .Values.auth.database .Values.auth.database .Values.auth.database .Values.auth.username -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.secretName" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.auth.postgresPassword | b64enc | quote }}
  password: {{ .Values.auth.password | b64enc | quote }}
  username: {{ .Values.auth.username | b64enc | quote }}
  database: {{ .Values.auth.database | b64enc | quote }}
  init-user.sql: {{ $script | b64enc | quote }}
{{- end }}
